# Generated by Django 6.0.7 on 2026-09-23 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_book_car_delete_cars_alter_order_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shifoxona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=155)),
                ('manzili', models.CharField(max_length=200)),
                ('xona_soni', models.PositiveIntegerField()),
                ('shifokor_soni', models.IntegerField()),
                ('bahosi', models.FloatField()),
                ('kunlik_narxi', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ochiqmi', models.BooleanField(default=False)),
                ('emaili', models.EmailField(max_length=254)),
                ('ochilgan_sana', models.DateField()),
                ('yaratilgan_vaqt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Shifoxona',
                'verbose_name_plural': 'Shifoxonalar',
            },
        ),
    ]
